server {
  listen 80;
  server_name localhost;

  location /halvest/uts-devops {
    alias /usr/share/nginx/html;
    try_files $uri $uri/ /halvest/uts-devops/index.html;
  }

  location /halvest/uts-devops/static {
    alias /usr/share/nginx/html/static;
  }

  error_page 404 /halvest/uts-devops/index.html;
}
