name: CI - DevOps UTS
on:
  push:
    branches: [ "development" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: |
          if [ -f package.json ]; then
            npm test
          else
            echo "No package.json found. Skipping tests."
          fi

  cache:
    name: Cache NPM Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

